### ISSUE TITLE
Get 401 Unauthorized when y use gateway.request_token

### ISSUE THREAD

**Issue by roseliux** [xero-gateway/xero_gateway#103]
My code is 

```
Gateway = XeroGateway::PrivateApp.new(YOUR_OAUTH_CONSUMER_KEY, YOUR_OAUTH_CONSUMER_SECRET, PATH_TO_YOUR_PRIVATE_KEY)

request_token = gateway.request_token
```

I get a 401 unauthorized response. 
I try to regenerate my cert and that did not work.
Any help please.

**Comment by nikz** [comment]
Hi @roseliux, most likely you'll need to check your consumer key and secret are set correctly and that you've created a private app in Xero. 

http://developer.xero.com is the best resource here, as this is really for bugs or issues in the Xero Gateway gem itself :)
