### ISSUE TITLE
Drop support for Ruby 1.9.3

### ISSUE THREAD

**Issue by nikz** [xero-gateway/xero_gateway#105]
We are looking at removing Ruby 1.9.3 support, as it's [long since stopped being officially supported](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/).

This will probably be as of the next release, and will be a soft failure (we'll stop running Travis builds against 1.9.3 rather than error out explicitly)

Any objections or comments please let us know!

**Comment by chibeepatag** [comment]
😿  😭  😢
