### ISSUE TITLE
400 Bad Request on fetching Request Token

### ISSUE THREAD

**Issue by stevenmaguire** [xero-gateway/xero_gateway#111]
Hello! Thanks for the gem! I am just getting started and I am encouraged by it so far. Unfortunately, I've run into an issue straight away and I don't have access to enough info from the gem to diagnose further, so I am hoping to get some feedback in this issue.

I am following the examples set forth in the README to spin up a new `XeroGateway::Gateway` and retrieve a request token and I am running into `400 Bad Request`s.

My app is a public app and I have double checked the callback domain, oauth key and oauth secret are accurate.

```ruby
# provider.key and provider.secret are legit
# callback_url matches the domain in the app
xero_oauth_consumer = XeroGateway::Gateway.new(provider.key, provider.secret)
begin
  xero_oauth_consumer.request_token(oauth_callback: callback_url).authorize_url
rescue OAuth::Unauthorized => e
  puts e.message
  puts e.backtrace
end
```
```
15:08:28 web.1          | 400 Bad Request
15:08:28 web.1          | /Users/stevenmaguire/.homebrew/var/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:216:in `token_request'
15:08:28 web.1          | /Users/stevenmaguire/.homebrew/var/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:136:in `get_request_token'
15:08:28 web.1          | /Users/stevenmaguire/.homebrew/var/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/xero_gateway-2.3.0/lib/xero_gateway/oauth.rb:41:in `request_token'
15:08:28 web.1          | /Users/stevenmaguire/.homebrew/var/rbenv/versions/2.3.4/lib/ruby/2.3.0/forwardable.rb:204:in `request_token'
```

Any ideas of what may be causing this? Any ideas on what I can do to share more detailed information?

**Comment by stevenmaguire** [comment]
Additionally, I have tested this via Postman and it does succeed in returning a request token, so I am leaning towards an issue with this gem. Do you agree?

**Comment by armstrjare** [comment]
Is callback URL right? When you have invalid callback URL (not matching one
set in Xero config) I think Xero returns 400 Bad Request

**Comment by stevenmaguire** [comment]
@armstrjare thanks for the response. I am getting back into this now. I've verified the domain in the Xero app config matches the domain of the callback url being sent to Xero API. The only difference I can tell is the callback url includes a port and the domain in the config does not. Do you believe that is related? Xero does not permit ports in their config.

OAuth callback domain: localhost 
callback_url: http://localhost:5000/connect/oauth1/xero/complete

**Comment by stevenmaguire** [comment]
The examples in this discussion seems to suggest the port does not matter, and I would expect that as well: https://community.xero.com/developer/discussion/11243525

**Comment by stevenmaguire** [comment]
After digging into the OAuth::Unauthorized error request, I get: 

`oauth_problem=parameter_rejected&oauth_problem_advice=Callback%20url%20is%20not%20in%20the%20registered%20callback%20domain`

**Comment by stevenmaguire** [comment]
Opened a discussion on the Xero community: https://community.xero.com/developer/discussion/53307345/
