### ISSUE TITLE
Undefined method for XeroGateway::Contact.account_number

### ISSUE THREAD

**Issue by abahaggag** [xero-gateway/xero_gateway#116]
I have a scenario which I need to contact account_number as it will contain a value related my the application that will be integrated with xero but when trying to access account_number I got undefined method account_number.
```
contacts = @gateway.get_contacts.response_item.map { |contact|
  {
      contact_id: contact.contact_id,
      name: contact.name,
      account_number: contact.account_number
  }
}
```
I checked xero_gateway/contact.rb and I found that it has attr_accessor for account_number but when I called XeroGateway::Contact.instance_methods(false) and the result doesn't include account_number and account_number=:
```
[:gateway, :gateway=, :errors, :contact_id, :contact_id=, :contact_number, :contact_number=, :status, :status=, :name, :name=, :first_name, :first_name=, :last_name, :last_name=, :email, :email=, :addresses, :addresses=, :phones, :phones=, :updated_at, :updated_at=, :bank_account_details, :bank_account_details=, :tax_number, :tax_number=, :accounts_receivable_tax_type, :accounts_receivable_tax_type=, :accounts_payable_tax_type, :accounts_payable_tax_type=, :is_customer, :is_customer=, :is_supplier, :is_supplier=, :default_currency, :default_currency=, :contact_groups, :contact_groups=, :address=, :address, :add_address, :phone=, :phone, :add_phone, :valid?, :save, :create, :update, :to_xml, :==]
```
The strange thing is when I checked @gateway.get_contacts.response_xml I found that it contains a node for AccountNumber.

Please help me with this. Thanks in advance

**Comment by armstrjare** [comment]
Must be a newer field, need to add it to the to_xml/from_xml methods on the Account type.

https://github.com/xero-gateway/xero_gateway/blob/master/lib/xero_gateway/account.rb#L66-L100

Can you submit PR adding this and updating the test fixture?
