### ISSUE TITLE
Getting invoices and their custom tracking categories

### ISSUE THREAD

**Issue by kebabbas** [xero-gateway/xero_gateway#123]
Hi,

When pulling invoices using the get_invoices method, I can retrieve data on an individual invoice using the relevant methods, e.g., the below gives me the subtotal for the first invoice retrieved by my get request

```
output = xerogateway.get_invoices(:modified_since => modified_since)
puts output.invoices.first.sub_total
```

However, I'd like to pull information related to the custom tracking categories I created for my invoices in Xero, in particular one I called "Customer type"

However, there does not appear to be a method to call that data from an individual invoice. For example,  in the above `output.invoices.first.methods` returns the following array, and it's not clear where the custom tracking options are in this

`[:==, :update, :create, :date, :valid?, :date=, :errors, :errors=, :invoice_number, :invoice_type, :currency_code, :currency_rate, :url, :reference, :to_xml, :line_items_downloaded?, :line_items, :contact, :payments, :currency_code=, :gateway, :gateway=, :save, :invoice_id, :reference=, :currency_rate=, :invoice_id=, :invoice_number=, :line_items_downloaded, :invoice_status, :due_date, :branding_theme_id, :line_amount_types, :fully_paid_on, :amount_due, :amount_paid, :amount_credited, :sent_to_contact, :updated_date_utc, :build_contact, :contact=, :accounts_payable?, :accounts_receivable?, :invoice_type=, :due_date=, :updated_date_utc=, :invoice_status=, :branding_theme_id=, :line_amount_types=, :line_items_downloaded=, :amount_due=, :amount_paid=, :amount_credited=, :sent_to_contact=, :url=, :payments=, :fully_paid_on=, :line_items=, :total, :sub_total, :add_line_item, :total_tax, :sub_total=, :total_tax=, :total=, :to_json, :`, :dclone, :to_query, :blank?, :acts_like?, :as_json, :present?, :presence, :to_param, :duplicable?, :deep_dup, :in?, :presence_in, :instance_values, :instance_variable_names, :with_options, :html_safe?, :try, :try!, :instance_of?, :kind_of?, :is_a?, :tap, :public_send, :class_eval, :remove_instance_variable, :singleton_method, :instance_variable_set, :define_singleton_method, :method, :public_method, :extend, :to_enum, :enum_for, :<=>, :===,:=~, :!~, :eql?, :respond_to?, :freeze, :inspect, :object_id, :send, :display, :to_s, :nil?, :hash, :class, :singleton_class, :clone, :dup, :itself, :taint, :tainted?, :untaint, :untrust, :untrusted?, :trust, :frozen?, :methods, :singleton_methods, :protected_methods, :private_methods, :public_methods, :instance_variable_get, :instance_variables, :instance_variable_defined?, :!, :!=, :__send__,:equal?, :instance_eval, :instance_exec, :__id__]`

**Comment by nikz** [comment]
@kebabbas I believe Tracking Categories are only [on line items](https://github.com/xero-gateway/xero_gateway/blob/master/lib/xero_gateway/line_item.rb#L109-L113), so you might have to try

`.invoices.first.line_items.first.tracking`
