### ISSUE TITLE
Adding Payroll and meta programming?

### ISSUE THREAD

**Issue by lordmortis** [xero-gateway/xero_gateway#124]
Hey there,

I'm adding payroll support in our fork (https://github.com/StirfireStudios/xero_gateway) and am hoping to issue a pull request.

Do you want all the parsing to be in the same style as the `Payment` class if any processing is required on the elements? or should I modify `BaseRecord` to allow for translation functions to be specified?

**Comment by lordmortis** [comment]
https://github.com/xero-gateway/xero_gateway/compare/master...StirfireStudios:feature/payroll_interface?expand=1 <- here is the diff

**Comment by armstrjare** [comment]
Thanks for this - looks cool!

I think what you've done there is fine for now regarding the translation 👍 

At some point it may be worthwhile extracting these out into seperate classes that encapsulate the serializer/deserializer login for each "field type" if we start adding a ton more of these... 

Can you submit a PR and some basic tests?

Cheers for this!

**Comment by lordmortis** [comment]
I've added a basic integration test for the gateway - but i'm not sure exactly how your units etc. work wrt the stubbed server ?

**Comment by nikz** [comment]
(Going to close this one @lordmortis, as I think the PR landed!)
