### ISSUE TITLE
Issue with 'save' method on invoice

### ISSUE THREAD

**Issue by kebabbas** [xero-gateway/xero_gateway#136]
Hi,

When I Authenticate with a private application as follows, in an irb environment

```
xerogateway = XeroGateway::PrivateApp.new(ENV.fetch("XERO_OAUTH_CONSUMER_KEY"),
                                      ENV.fetch("XERO_OAUTH_CONSUMER_SECRET"),
                                      "./certs/xero_privatekey.pem")
```

And try to post (ie, update) the due date on an invoice as follows, per the wiki's instructions, for example invoice number = `INV-11603`

`xerogateway.get_invoice("INV-11603").invoice.due_date = Time.parse("2018-06-30")`
`xerogateway.get_invoice("INV-11603").invoice.save`

I have the following error

```
XeroGateway::ApiException: XeroGateway::ApiException
        from /home/ubuntu/.rvm/gems/ruby-2.4.1@pobblebi/gems/xero_gateway-2.5.0/lib/xero_gateway/http.rb:127:in `handle_error!'
        from /home/ubuntu/.rvm/gems/ruby-2.4.1@pobblebi/gems/xero_gateway-2.5.0/lib/xero_gateway/http.rb:77:in `http_request'
        from /home/ubuntu/.rvm/gems/ruby-2.4.1@pobblebi/gems/xero_gateway-2.5.0/lib/xero_gateway/http.rb:12:in `http_post'
        from /home/ubuntu/.rvm/gems/ruby-2.4.1@pobblebi/gems/xero_gateway-2.5.0/lib/xero_gateway/gateway.rb:666:in `save_invoice'
        from /home/ubuntu/.rvm/gems/ruby-2.4.1@pobblebi/gems/xero_gateway-2.5.0/lib/xero_gateway/gateway.rb:257:in `update_invoice'
        from /home/ubuntu/.rvm/gems/ruby-2.4.1@pobblebi/gems/xero_gateway-2.5.0/lib/xero_gateway/invoice.rb:175:in `update'
        from /home/ubuntu/.rvm/gems/ruby-2.4.1@pobblebi/gems/xero_gateway-2.5.0/lib/xero_gateway/invoice.rb:160:in `save'
        from (irb):35
        from /home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/irb:11:in `<main>'
```

Any ideas what may be causing this exception?

Thanks

**Comment by nikz** [comment]
Hi @kebabbas,

It's likely that you're looking at two different instances of the invoice there - each `xerogateway.get_invoice("INV-11603")` will be returning a different instance of the Invoice object I believe.

I'm not sure why you're getting an exception - there should be a message with it that contains what Xero has said is wrong - perhaps check the Xero Developer Console and see what it says?

Cheers,

Nik

**Comment by armstrjare** [comment]
Rescue the exception and check what the full message is

Also - should the invoice ID be a UUID or does the invoice number itself
work?

Jared

**Comment by kebabbas** [comment]
Thanks both, there were two issues.

1) The developer console had this message `The document cannot be edited as it is currently dated before the period lock date, currently set at 31-Aug-2017`; so I went to try with a newer invoice. I'll investigate how to change the lock dates separately

2) Nikz point that each `xerogateway.get_invoice("INV-11603")` returns a different instance, so by doing

`INV11973 = xerogateway.get_invoice("INV-11973").invoice`
`INV11973.due_date = Time.parse("2018-04-20")`
`INV11973.save`

I was able to change the due date fine
