### ISSUE TITLE
Retrieving multiple invoices by IDs

### ISSUE THREAD

**Issue by jumzijie** [xero-gateway/xero_gateway#147]
Hi, how can I retrieve multiple invoices by providing the IDs?

I looked at the `get_invoices` method, but I can't seem to get it to work with `invoice_id` or `where` options:

```ruby
xero_invoice_ids = ['297c2dc5-cc47-4afd-8ec8-74990b8761e9', '297c2dc5-cc47-4afd-8ec8-74990b8761e9']

xero_gateway.get_invoices(invoice_id: xero_invoice_ids)
xero_gateway.get_invoices(invoice_id: xero_invoice_ids.join(','))
xero_gateway.get_invoices(invoice_id: xero_invoice_ids.first)

xero_gateway.get_invoices(where: "InvoiceID==#{xero_invoice_ids}")
xero_gateway.get_invoices(where: "InvoiceID==#{xero_invoice_ids.join(',')}")
xero_gateway.get_invoices(where: "InvoiceID==#{xero_invoice_ids.first}")
```

**Comment by nikz** [comment]
Heya @jumzijie! 

Looking at the [xero docs](https://developer.xero.com/documentation/api/invoices), I think you might have to use `ids` as the parameter. Does:

```rb
xero_gateway.get_invoices(ids: xero_invoice_ids.join(','))
```

Work?

**Comment by jumzijie** [comment]
Hey @nikz, thanks for your response!

Unfortunately, it didn't work.

Looking at the `get_invoices` method ([link](https://github.com/xero-gateway/xero_gateway/blob/e69e6528dc8c39b8bcfc619efce7078fa139437c/lib/xero_gateway/gateway.rb#L156)), it doesn't seem to support the `IDs` argument.

**Comment by nikz** [comment]
@jumzijie ah, dang looks like you're right.

Would be relatively easy to add - just copy [what's happening for ContactIDs](https://github.com/xero-gateway/xero_gateway/blob/e69e6528dc8c39b8bcfc619efce7078fa139437c/lib/xero_gateway/gateway.rb#L172) - I'd be happy to help.

Otherwise it might have to wait till either myself or @armstrjare get to it :)

**Comment by jumzijie** [comment]
@nikz Alright, have made a PR for it (my first ever open-source PR; please have mercy!). Please let me know if there's anything that I might have missed out, or how I might improve the PR. Thanks!

**Comment by armstrjare** [comment]
Thanks for contributing @jumzijie ! Nice 👍
