### ISSUE TITLE
'Create Payments' implementation

### ISSUE THREAD

**Issue by adonaldson** [xero-gateway/xero_gateway#37]
Hey guys (again),

I've started working on the ability to create Payments from the gem, based on the existing CreditNotes. I've not added any tests yet.

API Docs:
http://blog.xero.com/developer/api/payments/

My WIP branch:
https://github.com/adonaldson/xero_gateway/tree/create_payments

I've not created a pull request yet either as it's far from ready, but thought I'd let folk know it's in the works.

Cheers!

Andrew

**Comment by nikz** [comment]
Hiya - I think this is nearly ready in #87 if you wanted to finish it off?
