### ISSUE TITLE
Mistake in the readme

### ISSUE THREAD

**Issue by amxsv** [xero-gateway/xero_gateway#82]
Readme says that you should use this 
`redirect_to request_token(:oauth_callback => "http://www.something.com/xero/complete").authorize_url`
but it's doesn't work, you need to implement the callback url at the requestToken stage, not Authorize
`request_token = gateway.get_request_token(:oauth_callback => "http://www.something.com/xero/complete")`

**Comment by nikz** [comment]
Closing this, as I think it should be fixed now.
